# Fly.io configuration for Learn Vocabulary Backend
app = "learn-vocabulary-backend"
primary_region = "sin" # Singapore for better performance in Vietnam

[build]
  dockerfile = "./apps/backend/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1  # Keep at least 1 machine running to avoid cold starts

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[http_service.checks]]
  grace_period = "15s"  # Increase grace period for slower startup
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"  # Use correct health check endpoint

# Machine configuration optimized for NestJS
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
